### ISSUE TITLE
Convenience function for single axis figure

### ISSUE THREAD

**Issue by spencerahill** [spencerkclark/facets#31]
I use this in various Notebooks as a convenience function to get a single-axis figure but still using faceted's kwargs (see code below).  Any interest in including it or something like it in faceted proper?  Another alternative would be for faceted to return a single `ax` instance rather than a length-1 array in the case of a single-paneled plot.

Basically this is to avoid having to do 
```python
fig, axarr = faceted(1, 1, width=4)
ax = axarr[0]
```

and instead simply do
```python
fig, ax = facet_ax()
```

```python
def facet_ax(width=4, cbar_mode=None, **kwargs):
    """Use faceted to create single panel figure."""
    if cbar_mode is None:
        fig, axarr = faceted(1, 1, width=width, **kwargs)
        return fig, axarr[0]
    else:
        fig, axarr, cax = faceted(1, 1, width=width,
                                  cbar_mode=cbar_mode, **kwargs)
        return fig, axarr[0], cax
```

**Comment by spencerkclark** [comment]
I agree some sort of convenience functionality like this would be very nice.  I have this use-case a lot too!  I've gotten in the habit of doing something like this:
```python
fig, (ax, ), cax = faceted(1, 1, width=4, cbar_mode='single')
```
i.e. leveraging tuple unpacking to keep things all on one line.

In principle I'm not opposed to adding a separate function, but I feel like that could be awkward too in an interactive setting; e.g. it might mean you need to go back and import another function on the fly.  I know in the case of a single set of axes, @nathanieltarshish in the past has suggested always returning that instead of a length-one list, similar to `plt.subplots`.  What are your thoughts on that approach?  

I guess one drawback is that `axes` is no longer guaranteed to be an iterable, though I don't think that's something I personally rely on too much; maybe others do.

Regardless though, I'm happy to discuss this more and take a PR to address it.  It's been on my radar for some time, despite not having an open issue.  Thanks for bringing it up!

**Comment by spencerkclark** [comment]
> I guess one drawback is that `axes` is no longer guaranteed to be an iterable, though I don't think that's something I personally rely on too much; maybe others do.

Well, I guess my single-panel workaround and others' depend on this, but I wouldn't mind changing my code where necessary.  I don't automate plot making all that much.

**Comment by spencerahill** [comment]
>`fig, (ax, ), cax = faceted(1, 1, width=4, cbar_mode='single')`

Ahhh, I didn't realize that you could wrap `ax` in a tuple to do this as a one-liner. Thanks!  Honestly, that's sufficient for my needs for the time being.  I.e. don't expect a PR!

>I guess one drawback is that axes is no longer guaranteed to be an iterable, though I don't think that's something I personally rely on too much; maybe others do.

A way of avoiding this would be to implement it as a separate function.

**Comment by spencerkclark** [comment]
No worries; sounds good.  I agree a separate function is the least disruptive way to add this convenience option.  In re-reading your initial post, I now see that you also described the alternative I suggested 🤦‍♂.  Sorry, it's been a busy week...
