### ISSUE TITLE
saved figures are cropped; bounding box issue? 

### ISSUE THREAD

**Issue by nathanieltarshish** [spencerkclark/facets#41]
If I understand correctly, faceted should eliminate the need to save with `bbox_inches='tight'`, as the contents of the figure should automatically be sized to fit within the specified dimensions (determined by any two of `width`, `height`, `aspect`).   

When I save figures created with faceted, however, the result looks cropped and does not contain all of the content. Here is a minimal example:

```
import faceted
import numpy as np

# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, axis = faceted.faceted(1,1, width=3.0, height=3.0)

axis[0].plot(t, s)

axis[0].set(xlabel='time (s)', ylabel='voltage (mV)',
              title='About as simple as it gets, folks')
axis[0].grid()

fig.savefig("test.png", dpi=100)
```
yields the attached plot:

![test](https://user-images.githubusercontent.com/20796154/158722844-f68fa0b3-17db-44f5-8052-de19e8dd880b.png)

Is this a bug or am I misunderstanding the intended functionality of faceted? Thank you! 

Version number: faceted (0.2.1) and matplotlib (3.5.1),

**Comment by spencerkclark** [comment]
This is indeed expected.  `faceted` does not try to infer how large the padding around the axes should be.  It tries to use [some reasonable defaults](https://github.com/spencerkclark/faceted/blob/1bfa6636bde13e224b8dd695e47a175c659f4ca3/faceted/faceted.py#L15-L18), but these are not always optimal.  Fortunately it is possible to modify the padding manually:

```python
fig, (ax, ) = faceted.faceted(1, 1, width=3.0, height=3.0, left_pad=0.6, bottom_pad=0.5)

ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()
fig.savefig("test-plot2.png", dpi=100)
```
![test-plot2](https://user-images.githubusercontent.com/6628425/158806718-a49ba121-eee3-4cd7-96d7-56df3097e6ac.png)

In this case the overall figure is guaranteed to be 3x3 inches, and the aspect ratio of the axes is chosen such that the requested padding on the sides is respected.

So some manually tweaking is still needed to completely avoid using `"bbox_inches="tight"` when saving the figure.  Determining the optimal padding automatically is a tricky problem, since it depends on the size of the labels of the axes, and can change as one makes adjustments to those after the axes are created.  This is something that [proplot](https://proplot.readthedocs.io/en/stable/) -- a much more ambitious project than `faceted` -- tends to do pretty well, though its integration with other Python plotting tools (e.g. seaborn or nc-time-axis) is not always perfect, since it defines its own `Axes` class.

**Comment by nathanieltarshish** [comment]
Got it, thank you for the explanation. I am now able to adjust the padding so that I get all the content and match the dimensional constraints.
